### ISSUE TITLE
The logo on the Strimzi profile page does not align with the screen mode, whether it's in Light or Dark mode

### ISSUE THREAD

**Issue by UtkarshMishra12** [strimzi/.github#6]
Before 
1.

![image](https://github.com/strimzi/.github/assets/67385503/5eedd307-1170-4ead-bd59-6a6ff295da44)

[Link](https://github.com/strimzi)

2.
![image](https://github.com/strimzi/.github/assets/67385503/699fc67d-2d8a-4764-8e43-af9c3fcfb49e)

[Link](https://github.com/strimzi/.github)

After

Ideally, the logo should appear white in Dark mode and retain its normal appearance in Light mode.

![image](https://github.com/strimzi/.github/assets/67385503/063e2ef1-cb54-4b2c-b565-167b8e7e400f)

![image](https://github.com/strimzi/.github/assets/67385503/23363b5a-95d2-434b-86e8-0303cb3bc278)

**Comment by UtkarshMishra12** [comment]
I have taken the logo from the [CNCF Artwork repo.](https://github.com/cncf/artwork/tree/master)

Strimzi : [Link](https://github.com/cncf/artwork/blob/master/examples/sandbox.md#strimzi-logos)

CNCF: [Link](https://github.com/cncf/artwork/blob/master/examples/other.md#cncf-logos)

**Comment by scholzj** [comment]
I guess there will be always some mode where the logo will not be readable?

**Comment by scholzj** [comment]
I'm not sure how does that work. So I do not even know if that is possible or not. If you already have it, you can probably always open the PR right away instead of first discussing on the issue. At least the code will be visible as well.
